language: java
jdk: oraclejdk8
script: mvn package
deploy:
  provider: releases
  api_key:
    secure: D+NCt3hU8/gwOc1zhCsIS53ZV0d0fZlrfvN4PaT+isfHPiW5J2BKUa6ZqCWcmABXCavQlbulYC9nDC4oH81h8bTb3iMFKPY3VbZ6KPq/0h7TEL1xm9K9SRuNFJZRc99aWdPgVRgKAcbTgCGoZWJpypXs9EHqvqmzB1MXrryudhGp/EqNAIVL0lsPhTbsnhk2S2EbxW3yg72M7Fm8/xZg20LJWbL/ICYwHOacMzFE+NusmZbngyC7uRCkkr8iYVwKA+uHOtCym5bNv9PcG44eaQvBe64UkeydJr8LSMiVDA51fYimbwsimylrPGtO32MveZ6M7ueu5Hk0zRLD/xwZHp/ngpdrbvho85rlhjymCbVBiMtxq4Cn/VbPTwtg0+H8VnH7NrvS8rHGmeMpKUGfBcVglM9mRLjuqF80PlWYDuGis2v3HR2qkYBNJWlPqcP6xvzAjn8leuCggOZBkT1L6g7D7Ypkb4SIIGr48WXCJHqLxmmkcb3sESjnvZpadp3PkU27UR1eQp+Jpo/gSdPLLC9CZv1PVeZcyW/7hBIXAv6XIMDgRbt9Y7Oz+2VjmrTuEmZdABMl7IO7esshpEWvHGfcHbYoP0t5YdQorKyiiMdjBaN771LjIBodRenLPFpw30ZgPQVsALmE0OWJAr40EmfJ7/ikkEyYNI03Sc3K9f8=
  file: "target/*-bin.zip"
  skip_cleanup: true
  on:
    repo: medooze/sfu
